# Generated by Django 3.0.5 on 2020-05-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recycleManager',
            field=models.BooleanField(default=False),
        ),
    ]
